services:
  - name: tutorly-backend
    plan: starter
    region: us-west # Replace <REGION> with your desired region (e.g., us-west)
    buildCommand: npm install 
    startCommand: npm run build && node dist/server.js"

  - name: tutorly-frontend
    plan: starter
    region: us-west # Replace <REGION> with your desired region (e.g., us-west)
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run start
staticPublishPath: client/build
