export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
export const SIGNUP_FAIL = "REGISTER_FAIL";
export const SIGNIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNIN_FAIL = "LOGIN_FAIL";
export const LOAD_USER = "LOAD_USER";
export const UPDATE_ACCOUNT_STEP_ONE = "UPDATE_ACCOUNT_STEP_ONE";
export const UPDATE_ACCOUNT_STEP_TWO = "UPDATE_ACCOUNT_STEP_TWO";
export const UPDATE_ACCOUNT_STEP_ONE_FAIL = "UPDATE_ACCOUNT_STEP_ONE_FAIL";
export const UPDATE_ACCOUNT_STEP_TWO_FAIL = "UPDATE_ACCOUNT_STEP_TWO_FAIL";
export const UPDATE_USER_VIDEO_WALKTHROUGH_MODAL_CLOSE =
  "UPDATE_USER_VIDEO_WALKTHROUGH_MODAL_CLOSE";
export const UPDATE_USER_NEW_FEATURE_MODAL_CLOSE =
  "UPDATE_USER_NEW_FEATURE_MODAL_CLOSE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const GET_SCHOOL = "GET_SCHOOL";
export const UPDATE_SCHOOL_THEME_INFO = "UPDATE_SCHOOL_THEME_INFO";
export const UPDATE_DASHBOARD_PAGE_COUNTER =
  "UPDATE_DASHBOARD_PAGE_UPDATE_DASHBOARD_PAGE";
export const UPDATE_DASHBOARD_PAGE_COUNTER_TO_DEFAULT =
  "UPDATE_DASHBOARD_PAGE_COUNTER_TO_DEFAULT";
export const CHOOSE_THEME = "CHOOSE_THEME";
export const GET_SCHOOL_THEME = "GET_SCHOOL_THEME";
export const UPDATE_THEME_INFO = "UPDATE_THEME_INFO";
export const UPDATE_THEME_IMAGE = "UPDATE_THEME_IMAGE";
export const UPDATE_THEME_ABOUT_IMAGE = "UPDATE_THEME_ABOUT_IMAGE";
export const UPDATE_THEME_CONTACT_INFO = "UPDATE_THEME_CONTACT_INFO";
export const THEME_SETUP_ERROR = "THEME_SETUP_ERROR";
export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSE = "LOAD_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const PUBLISH_COURSE = "PUBLISH_COURSE";
export const RETRACT_COURSE = "RETRACT_COURSE";
export const ADD_COURSE_MODULE = "ADD_COURSE_MODULE";
export const LOAD_COURSE_MODULES = "GET_COURSE_MODULES";
export const ADD_COURSE_UNIT_TO_MODULE = "ADD_COURSE_UNIT_TO_MODULE";
export const REMOVE_COURSE_UNIT_FROM_MODULE = "REMOVE_COURSE_UNIT_FROM_MODULE";
export const UPDATE_MODULE_NAME = "UPDATE_MODULE_NAME";
export const DELETE_MODULE = "DELETE_MODULE";
export const LOAD_COURSE_UNIT = "LOAD_COURSE_UNIT";
export const UPDATE_COURSE_UNIT_NAME = "UPDATE_COURSE_UNIT_NAME";
export const UPDATE_COURSEUNIT_VIDEO = "UPDATE_COURSEUNIT_VIDEO";
export const UPDATE_COURSE_UNIT_PREVIEW_STATUS =
  "UPDATE_COURSE_UNIT_PREVIEW_STATUS";
export const ADD_ATTACHMENT_TO_COURSE_UNIT = "ADD_ATTACHMENT_TO_COURSE_UNIT";
export const DELETE_COURSE_UNIT = "DELETE_COURSE_UNIT";
export const REMOVE_ATTACHMENT_FROM_COURSE_UNIT =
  "REMOVE_ATTACHMENT_FROM_COURSE_UNIT";
export const ADD_COURSE_TO_CART = "ADD_COURSE_TO_CART";
export const REMOVE_COURSE_FROM_CART = "REMOVE_COURSE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const STUDENT_SIGNUP = "STUDENT_SIGNUP";
export const STUDENT_SIGNIN = "STUDENT_SIGNIN";
export const STUDENT_AUTH = "STUDENT_AUTH";
export const STUDENT_AUTH_FAILED = "STUDENT_AUTH_FAILED";
export const STUDENT_SIGNUP_FAIL = "STUDENT_SIGNUP_FAIL";
export const STUDENT_SIGNIN_FAIL = "STUDENT_SIGNIN_FAIL";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";
export const SHOW_PAYMENT_MODAL = "SHOW_PAYMENT_MODAL";
export const REMOVE_PAYMENT_MODAL = "REMOVE_PAYMENT_MODAL";

export const LOAD_NOTIFICATION_DATA = "LOAD_NOTIFICATION_DATA";
export const RESET_NOTIFICATION_UPDATE_DATA = "RESET_NOTIFICATION_UPDATE_DATA";

export const LOAD_STUDENT_NOTIFICATION_DATA = "LOAD_STUDENT_NOTIFICATION_DATA";
export const RESET_STUDENT_NOTIFICATION_DATA =
  "RESET_STUDENT_NOTIFICATION_DATA";

export const LOAD_SUBDOMAIN_IN_STATE = "LOAD_SUBDOMAIN_IN_STATE";

export const DISPLAY_TUTORIALS_MODAL = "DISPLAY_TUTORIALS_MODAL";
export const CLOSE_TUTORIALS_MODAL = "CLOSE_TUTORIALS_MODAL";
export const LOAD_ACTIVE_TUTORIAL = "LOAD_ACTIVE_TUTORIAL";
export const LOAD_TUTORIAL_LIST = "LOAD_TUTORIAL_LIST";
export const EMPTY_TUTORIAL_LIST = "EMPTY_TUTORIAL_LIST";
export const EMPTY_ACTIVE_TUTORIAL = "EMPTY_ACTIVE_TUTORIAL";

export const DISPLAY_VIDEO_UNIT_PREVIEW_MODAL =
  "DISPLAY_VIDEO_UNIT_PREVIEW_MODAL";
export const CLOSE_VIDEO_UNIT_PREVIEW_MODAL = "CLOSE_VIDEO_UNIT_PREVIEW_MODAL";
export const LOAD_ACTIVE_VIDEO_PREVIEW = "LOAD_ACTIVE_VIDEO_PREVIEW";
export const LOAD_COURSE_PREVIEWABLE_LIST = "LOAD_COURSE_PREVIEWABLE_LIST";
export const EMPTY_COURSE_PREVIEWABLE_LIST = "EMPTY_COURSE_PREVIEWABLE_LIST";
export const EMPTY_ACTIVE_VIDEO_PREVIEW = "EMPTY_ACTIVE_VIDEO_PREVIEW";

export const TUTOR_SIGNUP = "TUTOR_SIGNUP";
export const TUTOR_SIGNIN_FAIL = "TUTOR_SIGNIN_FAIL";
export const TUTOR_SIGNUP_FAIL = "TUTOR_SIGNUP_FAIL";
export const TUTOR_SIGNIN = "TUTOR_SIGNIN";
export const TUTOR_AUTH = "TUTOR_AUTH";
export const TUTOR_LOGOUT = "TUTOR_LOGOUT";
export const TUTOR_AUTH_FAILED = "TUTOR_AUTH_FAILED";

// cuurency types here
export const SET_CURRENCY_AND_EXCHANGE_RATE = "SET_CURRENCY_AND_EXCHANGE_RATE";
export const SET_CURRENCY_AND_EXCHANGE_RATE_FAIL =
  "SET_CURRENCY_AND_EXCHANGE_RATE_FAIL";